### PR TITLE
Licence added and UX adjustments for testing

### PR DESCRIPTION
**Pull request by shanecoughlan**
Added license files throughout the project.

Removed some commas flagged as unneeded by WebSphere in some files
(noted in comments in each file)

Biggest change to client/components/modules.controls.component.jsx
needs testing to ensure it did not break:
* Removed commas flagged as unneeded by WebSphere
 * Changed opacity to 0.5 for testing
 * Moved the button position for testing (added "top: '20%'" to const
styles

### CODE REVIEW

**Comment by sonicviz** [comment]
Looking good! Will run a test later. Ty!

**Comment by sonicviz** [comment]
Getting errors trying to run quasar:

G:\Meteor Projects\quasar>meteor

[[[[[ ~\G\Meteor Projects\quasar ]]]]]

 

=> Started proxy.

=> Started MongoDB.

=> Errors prevented startup:

 

   While processing files with templating (for target web.browser):

   client/index.html:1: Expected one of: <body>, <head>, <template>

 

   While processing files with jsx (for target web.browser):

   client/components/modules/error.component.jsx:22:14: client/components/modules/error.component.jsx:

   Unexpected token (22:14)

 

=> Your application has errors. Waiting for file change.

 

Seems related to new code:

const FontIcon;

FontIcon = MUI;

 

Changed from:

const {FontIcon} = MUI;

 

Q: Did you run meteor and test this before committing and pushing?

**Comment by shanecoughlan** [comment]
My bad. I did not compile, just pushed for review. Will resubmit with license file changes and one file with example comments.

**Comment by sonicviz** [comment]
Pro Tip: Never ever ever (or even EVER!) commit without testing first;-/

**Pull request merged**
